name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint@8.45.0 eslint-config-next@14.0.4
          [ -f .eslintrc.json ] || cp .eslintrc.json.example .eslintrc.json
      - name: ESLint Report
        run: npm run lint
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@15.10.0 stylelint-config-recommended@13.0.0 stylelint-order@6.0.3
          [ -f .stylelintrc.json ] || cp .stylelintrc.json.example .stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"